name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v5

      - name: nix flake check
        run: nix flake check --show-trace

      - name: build NixOS system
        run: nix build --print-out-paths .#nixosConfigurations.devbox.config.system.build.toplevel
