name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: x86_64-linux
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    env:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        accept-flake-config = true
    steps:
      - uses: actions/checkout@v4

      - name: Build NixOS system
        run: nix build --no-link --print-out-paths ".#nixosConfigurations.devbox-${{ matrix.system }}.config.system.build.toplevel"

      - name: Build Lima image
        run: nix build --no-link --print-out-paths ".#packages.${{ matrix.system }}.devbox-image"
